site_name: Daniel Wenbo's Blog
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  alternate:
    - name: en -English
      link: /docs/en
      lang: en
    - name: zh -Chinese
      link: /docs/zh
      lang: zh
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mendax1234

#plugins:
#  - blog

nav:
  - index.md
  - Blog:
    - blog/index.md 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/mendax1234/mendax1234.github.io"  target="_blank" rel="noopener">Daniel Wenbo</a>