# Project Information
site_name: Daniel Wenbo's Site

# Repository
repo_name: mendax1234/MySite
repo_url: https://github.com/mendax1234/mendax1234.github.io

# Copyright
copyright: Copyright &copy; 2023 Daniel Wenbo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  alternate:
    - name: en -English
      link: /docs/en
      lang: en
    - name: zh -Chinese
      link: /docs/zh
      lang: zh
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mendax1234/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Daniel_Wenbo

plugins:
  - blog
  - search

nav:
  - index.md
  - Blog:
    - blog/index.md 
    - 2023:
      - blog/posts/hello-world.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
