name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build EN docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.yml
      - name: Build ZH docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.zh.yml  
      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
      - run: pip install -r requirements.txt
      # - run: mkdocs gh-deploy --force